# Archivo de configuración del Algoritmo Genético

image:
  path: "images/mapa.png"
  resolution: [128, 128]

algorithm:
  pop_size: 50
  n_triangles: 50
  generations: 20000
  target_fitness: 1.0   # Si el fitness alcanza este valor, se frena el algoritmo (poner 0 para no usar)

  selection:
    method: "deterministic_tournament"  # elite/roulette/universal/boltzmann/ranking/deterministic_tournament/probabilistic_tournament

  crossover:
    method: "one_point"

  mutation:
    method: "nouniform" # gene/uniform/nouniform
    rate: 0.1

  survival:
    method: "additive" # additive/exclusive

output:
  dir: "results"         # Carpeta donde se guardarán los resultados
  save_step: 500          # Guardar imagen cada N generaciones (0 para no guardar imágenes intermedias)

benchmark:
  images:
    - "images/polonia.png"
    - "images/brasil.png"
    - "images/mickeymouse.png"
    - "images/nike.png"
    - "images/señal.png"
    - "images/mapa.png"
